version : "3.6"

services :

  sh-model-api:
    image: emartps/sh-model-api:latest
    container_name: model_api_container
    volumes:
      - ./models/bioinfoRepo_bert:/api/bioinfoRepo_bert
    ports:
      - "5800:5800"
    expose:
      - "5800"

  somef-api:
    image: emartps/somef-api:latest
    container_name: somef_api_container
    expose:
      - "5300"
    
  sh-worker:
    image: emartps/sh-worker:latest
    container_name: worker_container

  